# Generated by Django 4.1 on 2022-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variations_variations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='variations_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100),
        ),
    ]
