# Generated by Django 4.1 on 2022-08-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variations_variations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='variations_category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], max_length=100),
        ),
    ]
