# Generated by Django 4.1 on 2022-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=8081787322, max_length=50),
            preserve_default=False,
        ),
    ]
